### ISSUE TITLE
Se debe refactorizar el código repetido

### ISSUE THREAD

**Issue by evolentini** [leaiava/TP1_TSE#2]
El código de control de los limites del parámetro se repite cuatro veces, debería estar en una función interna, por ejemplo dentro de la misma `LedToMask()`

https://github.com/leaiava/TP1_TSE/blob/13f4cbbd518a68ee3c4a9029aad9cd90e8063e86/src/leds.c#L24-L31

https://github.com/leaiava/TP1_TSE/blob/13f4cbbd518a68ee3c4a9029aad9cd90e8063e86/src/leds.c#L36-L43

https://github.com/leaiava/TP1_TSE/blob/13f4cbbd518a68ee3c4a9029aad9cd90e8063e86/src/leds.c#L58-L69

https://github.com/leaiava/TP1_TSE/blob/13f4cbbd518a68ee3c4a9029aad9cd90e8063e86/src/leds.c#L74-L85

**Comment by leaiava** [comment]
Corregido en vs_B. 

Se hizo como lo sugerido, se colocó el código dentro de LedToMask()
