### ISSUE TITLE
No se si justifica dos funciones para consultar el estado

### ISSUE THREAD

**Issue by evolentini** [leaiava/TP1_TSE#3]
El código de las funciones es prácticamente idéntico, de mantener las dos funciones yo haría que una, por ejemplo `LedsIsOn()`, utilice a la otra para generar el resultado. La idea de no tener código repetido es facilitar las modificaciones futuras cuando hay cambios para hacer, por ejemplo si hay que agregar soporte para lógica directa y negada al mismo tiempo.

**Comment by leaiava** [comment]
Corregido en vs_B.

Se hizo como lo sugerido, ahora `LedsIsOn()` utiliza `LedIsOff()`
